config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  resources :projects

  resources :donates

  resources :users
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :rewards

  get 'login' => 'user_sessions#new', as: 'login'
  get 'logout' => 'user_sessions#destroy', as: 'logout'

end

app/models/donate.rb
class Donate < ActiveRecord::Base
	belongs_to :donor, class_name: 'User'
	belongs_to :project
	# validates :amount, presence => true
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :rewards
	accepts_nested_attributes_for :rewards
	
	has_many :donates
	belongs_to :owner, class_name: "User"

	accepts_nested_attributes_for :donates

end

app/models/reward.rb
class Reward < ActiveRecord::Base
	belongs_to :project
	#has_many :users?
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def not_authenticated
  	redirect_to login_path, alert: "PLease log in first"
  end
end

app/controllers/donates_controller.rb
class DonatesController < ApplicationController
  #before_filter :ensure_logged_in, only: [:create, :destroy]
  #before_filter :load_project

	def show
	  @donate = Donate.find(params[:id])
	end

	def create
		@donate = Donate.new(donate_params)
		@donate.donor = current_user
		@donate.project_id = params[:donate][:project_id]

		@donate.project.amount_funded = @donate.project.donates.pluck(:amount).sum
		@donate.project.save

	  	respond_to do |format|
	  		if @donate.save #can we put .submit or .donate here?
	  			format.html {redirect_to project_path(@donate.project), notice: 'Thanks for donating!' }
	  			format.js {} # will look for create.js.erb - need to make it
	  		else
	  			format.html { render 'projects/show', alert: 'your money is unwanted' }
	  			format.js {} #lookning for same create.js
	  		end
	  	end
	end

	def destroy
		@donate = Donate.find(params[:id])
		@donate.destroy
	end

private

def donate_params
	params.require(:donate).permit(:amount)
end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	# before_action :require_login, except :index

  def index
  	@projects = Project.all
  end

  def new
  	@project = Project.new
  end

  def create
  	@project = Project.new(project_params)
  	if @project.save
  		redirect_to projects_url
  	end
   end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(project_params)
      redirect_to project_url(@project)
    end
   end

  def destroy
  	@project = Project.find(params[:id])
  	@project.destroy
  	redirect_to project_path
  end

  def show
  	@project = Project.find(params[:id])
  end


  def edit
  	@project = Project.find(params[:id])
  end

  private
  def project_params
  	params.require(:project)
          .permit(:name,
            :funding_goal,
            :end_date,
            :start_date,
            :description,
            :amount_funded,
            donates_attributes: [:id, :amount]
            )
  end


end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
  end

  def create
  	if @user = login(params[:email], params[:password], params[:remember_me])
  		redirect_back_or_to(root_url, notice: 'Login successful')
  	else
  		flash.now[:alert] = "Login failed"
  		render 'new'
  	end
  end

  def destroy
  	logout
  	redirect_to root_url, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		auto_login(@user)
  		redirect_to projects_url
  	else
  		render 'new'
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donate_helper.rb
module DonateHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/donate/create.html.erb
<h1>Donate#create</h1>
<p>Find me in app/views/donate/create.html.erb</p>

app/views/donate/destroy.html.erb
<h1>Donate#destroy</h1>
<p>Find me in app/views/donate/destroy.html.erb</p>

app/views/donate/show.html.erb
<h1>Donate#show</h1>
<p>Find me in app/views/donate/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfunder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="nav">
    Welcome to <%= link_to "Crowdfunder", projects_path %>!
  	<% if current_user %>
      You're logged in as <%= current_user.first_name %> <%= current_user.last_name %>.
  	  <%= link_to "Edit Profile", edit_user_path(current_user.id) %> |
  	  <%= link_to "Logout", :logout %>
  	<% else %>
  	  <%= link_to "Register", new_user_path %> |
  	  <%= link_to "Login", :login %>
  	<% end %>
  </div>
  <div>
  	<p id="notice"><%= flash[:notice] %></p>
	<p id="alert"><%= flash[:alert] %></p>

<%= yield %>

</body>
</html>

app/views/projects/_creation_form.html.erb
<%= form_for(@project)  do |f|  %>

	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>

	<div class="field">
		<%= f.label :description %><br />
		<%= f.text_field :description %>
	</div>

	  <p>Rewards</p>
	  <div>
	    <%= f.label :image %>
	    <%= f.file_field :image %>
	  <div>

	  <%= f.fields_for :rewards do |r| %>
	    <%= render 'reward_fields', :f => r %>
	  <% end %>
	  </div>
  	</br>
	<div class="field">
		<%= f.label :funding_goal %><br />
		$<%= f.number_field :funding_goal %>
	</div>
	Project end date
	<div class="field">
		<%= f.datetime_select :end_date, ampm: true, default: 1.months.from_now, discard_hour: true, class: "form_fields" %><br>
	</div>

	<div>
		<%= f.hidden_field :start_date, :value => Time.now %>
	</div>
	<div>
		<%= f.hidden_field :owner, :value => current_user %>
	</div>
	<div>
		<%= f.hidden_field :amount_funded, :value => 0 %>
	</div>
	<div class="action">
		<%= f.submit %>
	</div>

<% end %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>

	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>

	<div class="field">
		<%= f.label :description %><br />
		<%= f.text_field :description %>
	</div>
  	</br>
	<div class="field">
		<%= f.label :funding_goal %><br />
		$<%= f.number_field :funding_goal %>
	</div>
	Project end date
	<div class="field">
		<%= f.datetime_select :end_date, ampm: true, default: 1.months.from_now, discard_minute: true, discard_hour: true, class: "form_fields" %><br>
	</div>

	<div>
		<%= f.hidden_field :start_date, :value => Time.now %>
	</div>
	<div class="action">
		<%= f.submit %>
	</div>

<% end %>

app/views/projects/_reward_field.html.erb
<div>
  <%= f.label :amount %>
  <%= f.text_field :amount %>
</div>

<div>
  <%= f.label :description %>
  <%= f.text_field :description %>
</div>

app/views/projects/_reward_fields.html.erb
<div>
  <%= f.label :amount %>
  <%= f.text_field :amount %>
</div>

<div>
  <%= f.label :description %>
  <%= f.text_field :description %>
</div>

app/views/projects/create.html.erb
FKKFKJF

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

app/views/projects/index.html.erb
<h3>Projects</h3>

<div id="project_details">
	<% @projects.each do |individual_project| %>
		<div id="project_name">
		<%= link_to individual_project.name, projects_path(individual_project) %>
		</div>
		<div id="project_description">
			<%= truncate(individual_project.description, length: 60 ) {link_to "see more", project_paths(individual_project)} %>
		</div>
		<div id="project_funding">
			Funds raised: $<%= individual_project.amount_funded %> of $<%= individual_project.funding_goal %>
		</div>

	<% end %>

<%= link_to 'Back', projects_path %> |
<%= link_to 'Start a Project', "/projects/new" %>

app/views/projects/new.html.erb
<% if logged_in? %>
	<h1>Create a new project!!</h1>
	<%= render 'creation_form' %>
	<%= link_to 'Back', projects_path %>
<% else %>
	<p>
	Please <%= link_to "log in", "/login" %>  or <%= link_to "create an account", "/users/new" %> to be able to create a project.
	</p>
<% end %>

app/views/projects/reward.html.erb
<h1>Rewards for <%= @project.name %> </h1>

<% render 'reward_field' %>

app/views/projects/show.html.erb
<h1> <%= @project.name %></h1>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>


<div id="project_description">
	<%= @project.description %>
</div>

<div id="project_funding">
	Funds raised: $<%= @project.amount_funded %> of $<%= @project.funding_goal %>
	<br>This project is <%= ((@project.amount_funded.to_f / @project.funding_goal) * 100).round %>% funded!<br>
</div>


<!-- make this page prettier later, using partials? -->

<% if logged_in? %>
<!-- fix this! -->
	<% if current_user.id == @project.owner_id %>
		<div id="project_timing">
			<% ending = @project.end_date %>
			<% current = DateTime.now %>
			<!-- There must be a better way to display dates in this format. Oh well! -->
			Your project is due to end on <%=ending.month%>/<%=ending.day%>/<%=ending.year%>! That's only <%= ending - current.day%> days from now!
		</div>
	<% else %>
		<%= form_for Donate.new do |f| %>
			<%= f.hidden_field :project_id, value: @project.id %>

			<%= f.select :amount do %>
				<option value="5">$5</option>
				<option value="10">$10</option>
				<option value="20">$20</option>
				<option value="100">$100</option>
				<option value="500">$500</option>
			<% end %>

			<%= f.submit "Donate!" %>
		<% end %>
	<% end %>
<% end %>






<%= link_to 'Back', projects_path %> |
<%= link_to 'Start a Project', "/projects/new" %>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
  	<%= label_tag :email %><br />
  	<%= text_field_tag :email %>
  </div>
   <div class="field">
  	<%= label_tag :password %><br />
  	<%= password_field_tag :password %>
  </div>

  <div class="field">
  	<%= label_tag :remember_me %><br />
  	<%= check_box_tag :remember_me %>
  </div>

   <div class="actions">
  	<%= submit_tag "Login" %>
  </div>
 <% end %>

app/views/user_sessions/new.html.erb
<h1>Log in</h1>

<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>

app/views/users/_userform.html.erb
<%= form_for @user do |f| %>

  <div class="field">
  	<%= f.label :first_name %>
  	<%= f.text_field :first_name %>
  </div>

  <div class="field">
  	<%= f.label :last_name %>
  	<%= f.text_field :last_name %>
  </div>

  <div class="field">
  	<%= f.label :email %>
  	<%= f.text_field :email %>
  </div>

  <div class="field">
  	<%= f.label :password %>
  	<%= f.password_field :password %>
  </div>

  <div class="field">
  	<%= f.label :password_confirmation %>
  	<%= f.password_field :password_confirmation %>
  </div>

  <div class="field">
  	<%= f.submit %>
  </div>

<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'userform' %>